/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseFormCourseIdIndexRouteImport } from './routes/course-form/$course-id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseFormCourseIdIndexRoute = CourseFormCourseIdIndexRouteImport.update({
  id: '/course-form/$course-id/',
  path: '/course-form/$course-id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course-form/$course-id': typeof CourseFormCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course-form/$course-id': typeof CourseFormCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course-form/$course-id/': typeof CourseFormCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/course-form/$course-id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course-form/$course-id'
  id: '__root__' | '/' | '/course-form/$course-id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseFormCourseIdIndexRoute: typeof CourseFormCourseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-form/$course-id/': {
      id: '/course-form/$course-id/'
      path: '/course-form/$course-id'
      fullPath: '/course-form/$course-id'
      preLoaderRoute: typeof CourseFormCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseFormCourseIdIndexRoute: CourseFormCourseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
